language: scala
jdk:
  - openjdk8
scala:
  - 2.13.0
script:
  - sbt -J-Xms4G -J-Xmx4G +test docs/tut scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete -print
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete -print
